cb:
	FORCE=0 ./run.sh ~/work/pcpipe/data/orfs ~/work/pcpipe/data/TOV_43_all_contigs_predicted_proteins.faa ~/work/pcpipe/out
	
	#FORCE=1 ./run.sh ~/work/pcpipe/data/min ~/work/pcpipe/data/TOV_43_all_contigs_predicted_proteins.faa ~/work/pcpipe/out
