cb:
	./run.sh ~/work/pcpipe/data/orfs ~/work/pcpipe/data/min-clus.fa ~/work/pcpipe/out

#./run.sh ~/work/pcpipe/data/min ~/work/pcpipe/data/TOV_43_all_contigs_predicted_proteins.faa ~/work/pcpipe/out
